### ISSUE TITLE
Sudden Error- R session Failure

### ISSUE THREAD

**Issue by desmodus1984** [statgenlmu/coala#194] opened 2018-06-28 01:09 UTC
Hi, I was testing the software since I want to simulate populations to then simulate hybridization and with the simple example- 
model <- coal_model(20, 2000) +
   feat_mutation(2) +
   feat_recombination(1) +
   sumstat_tajimas_d()
 stats <- simulate(model, seed = 15)
 plot(density(stats$tajimas_d, na.rm = TRUE), 
      main = "Neutral Distribution of Tajiam's D")

running stats... the session failed. Several times, also, installing coala was annoying since several packages needed independent installation.

**Comment by paulstaab** [comment] 2018-06-28 06:41
Since you choose not to include an error message in your report, I can only guess what the problem is here. You are maybe running in a problem with my other package scrm, which fails when it is used to simulate many loci:

https://github.com/scrm/scrm-r/issues/38

If this seems to affecting you, I recommend that you either use the previous version of `scrm` or a different simulator like ms for now.

As for the "annoying" installation: You should be able to install coala with a `install.packages("coala")` in R, which is the standard way of installing R packages. If this does not work for you, then this is their your fault (likely) or a problem with the install.packages funktion from base R (unlikely), but not a problem of coala.

I am closing this issue because it does not seem to be coala related. Feel free to reopen it if you believe it does.

**Closed by paulstaab** 2018-06-28 06:41 UTC
